application: lag-meetup
version: 1
runtime: go
api_version: go1

handlers:
    - url: /static
      static_dir: static
    - url: /
      static_files: static/index.html
      upload: static/index.html
    - url: /.*
      script: _go_app
